# Generated by Django 5.0.6 on 2024-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('Complete', models.BooleanField(default=False)),
                ('date_field', models.DateTimeField()),
                ('categories', models.ManyToManyField(to='task_category.categorymodel')),
            ],
        ),
    ]
