# Generated by Django 5.0.6 on 2024-07-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
