# Generated by Django 5.0.6 on 2024-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0002_carbrand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
