# Generated by Django 5.0.6 on 2024-07-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[('DEPOSIT', 'Dposit'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN', 'Loan'), ('LOAN_PAID', 'Loan Paid')], null=True),
        ),
    ]
