# Generated by Django 5.0.6 on 2024-08-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_initial_deposit_date_userbankaccount_initial_deposite_date_and_more'),
        ('transactions', '0005_rename_reciver_transfermodel_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermodel',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.userbankaccount'),
        ),
    ]
