# Generated by Django 5.0.6 on 2024-08-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transfermodel_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfermodel',
            name='account',
        ),
    ]
