# Generated by Django 5.0.6 on 2024-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
