# Generated by Django 5.0.6 on 2024-07-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbankaccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='email',
        ),
    ]
