# Generated by Django 5.0.6 on 2024-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorice',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
