# Generated by Django 5.0.6 on 2024-07-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='brand_name',
        ),
    ]
