# Generated by Django 5.0.6 on 2024-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
