# Generated by Django 5.0.6 on 2024-07-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carmodel_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='count',
        ),
    ]
